#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

resource_dir=$(dirname $0)

export TMPDIR=/tmp

# Read inputs
payload=$(mktemp $TMPDIR/request-payload.XXXXXX)
cat > $payload <&0

source $resource_dir/init.sh

npm info --json "@${scope}/${package}" | jq -M '[{version:.["dist-tags"].latest}]' >&3
